AllCops:
  TargetRubyVersion: 2.3

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'lib/antaeus-sdk/resource.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods.
Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/antaeus-sdk/api_client.rb'

#Metrics/AbcSize:
#  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 8

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/ExtraSpacing:
  Exclude:
    - 'antaeus-sdk.gemspec'

